version: 2.1
orbs:
  win: circleci/windows@5.0
jobs:
  build:
    executor: win/default
    steps:
      - checkout
      - run: |
          yarn install
          yarn supabase -h
workflows:
  my-workflow:
    jobs:
      - build
